[package]
name = "youtube-desktop"
version = "0.1.0"
edition = "2021"
description = "Desktop wrapper for YouTube"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-ico", "image-png", "unstable"] }
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
winreg = "0.52"

[[bin]]
name = "youtube-desktop"
path = "src/main.rs"
